# yazi.toml
[manager]
show_hidden = true
linemode = "mtime"
show_symlink = true
sort_dir_first = true
sort_by = "extension"

[opener]
nvim = [{ run = 'nvim "$@"', block = true, for = "unix" }]

[open]
prepend_rules = [
    # Config files
    { name = "*.conf", use = ["edit", "nvim"] },
    { name = "*.zsh", use = ["edit", "nvim"] },
    { name = "*.yaml", use = ["edit", "nvim"] },
    { name = "*.toml", use = ["edit", "nvim"] },
]

append_rules = [
    # Folder
    { name = "*/", use = ["edit", "nvim", "open", "reveal"] },
    # Text
    { mime = "text/*", use = ["edit", "nvim", "reveal"] },
    # JSON
    { mime = "application/{json,ndjson}", use = ["edit", "nvim", "reveal"] },
    { mime = "*/javascript", use = ["edit", "nvim", "reveal"] },
    # Empty file
    { mime = "inode/empty", use = ["edit", "nvim", "reveal"] },
    # Fallback
    { name = ".*", use = ["edit", "nvim"] },
    { name = "*", use = ["edit", "nvim", "open", "reveal"] },
]
